### ISSUE TITLE
Service Status (in Windows Services) rapidly changes between "Starting" and "Running" and program doesn't work.

### ISSUE THREAD

**Issue by Dwedit** [hirschmann/nbfc#1003]
So, I'm setting the service rapidly switch between "Starting" and "Running" in the services manager.  It's doing this every 2 seconds.

![service starting](https://i.imgur.com/1RjdbS9.png) ![service running](https://i.imgur.com/jVDbZmh.png)

When I try to stop the service, I see this message:

![service stopping error](https://i.imgur.com/NlJzQ2Y.png)

Then I look at settings page, and see that it was repeatedly restarting itself on failure, and it left 4900+ events in the Event Log about being unable to start:

![event viewer](https://i.imgur.com/1SQqftK.png)

**Comment by Dwedit** [comment]
After running the service in a debugger, I see this exception:

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Failed to access CPU temperature sensors(s).
  Source=StagWare.Hardware
  StackTrace:
   at StagWare.Hardware.HardwareMonitor.InitializeCpuSensors()
   at StagWare.Hardware.HardwareMonitor.get_CpuTemperatures()
   at StagWare.Plugins.Generic.CpuTemperatureMonitor.GetTemperature()
   at StagWare.FanControl.FanControl.TimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

edit:

In this function, I see 7 sensors, all of which are type "Load" and not type "Temperature", so it sees no temperature sensors.

```
        private static ISensor[] GetCpuTemperatureSensors(IHardware cpu)
        {
            var sensors = new List<ISensor>();
            cpu.Update();

            foreach (ISensor s in cpu.Sensors)
            {
                if (s.SensorType == SensorType.Temperature)
                {
                    string name = s.Name.ToUpper();

                    if (name.Contains("PACKAGE") || name.Contains("TOTAL"))
                    {
                        return new ISensor[] { s };
                    }
                    else
                    {
                        sensors.Add(s);
                    }
                }
            }

            return sensors.ToArray();
        }
```

**Comment by Dwedit** [comment]
It appears that "OpenHardwareMonitor" is out of date, it's 2 years behind the current version.  I was able to get this working by copy-pasting in the newer Intel CPU code into "Plugins\OpenHardwareMonitor\Hardware\CPU\IntelCPU.cs"

**Comment by Dwedit** [comment]
This was caused by the program throwing an exception, then the service manager restarting it repeatedly.  So this is a symptom, not the underlying bug.
