### ISSUE TITLE
NbfcService service error after waking from Sleep Mode 

### ISSUE THREAD

**Issue by oldbk** [hirschmann/nbfc#132]
**Asus n550jv**
Hi, i've got next errors in mmc on windows 8.1

**Application: NbfcService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException**
Stack:
   at System.Array.Copy(System.Array, Int32, System.Array, Int32, Int32, Boolean)
   at System.Collections.Generic.Queue`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetCapacity(Int32)
   at System.Collections.Generic.Queue`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Enqueue(Double)
   at StagWare.FanControl.ArithmeticMeanTemperatureFilter.FilterTemperature(Double)
   at StagWare.FanControl.FanControl.TimerCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Source array was not long enough. Check srcIndex and length, and the array's lower bounds.**

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at StagWare.FanControl.ArithmeticMeanTemperatureFilter.FilterTemperature(Double temperature)
   at StagWare.FanControl.FanControl.TimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Failed in handling the PowerEvent. The error that occurred was: System.TimeoutException: EC initialization timed out.**
   at StagWare.FanControl.FanControl.InitializeRegisterWriteConfigurations()
   at NbfcService.NoteBookFanControlService.OnPowerEvent(PowerBroadcastStatus powerStatus)
   at System.ServiceProcess.ServiceBase.DeferredPowerEvent(Int32 eventType, IntPtr eventData).

![2016-11-02_014356](https://cloud.githubusercontent.com/assets/6886009/19910425/e9f9b36a-a09d-11e6-8a93-d37be4204d4b.png)

**Comment by hirschmann** [comment]
Seems like NBFC fails to access the hardware after standby.
Does this happen every time the system wakes up or infrequently?

**Comment by oldbk** [comment]
sure infrequently

**Comment by hirschmann** [comment]
I'll look into it, but I can't reproduce this error, so I'm not sure if I can do anything about it.

When this error occurs, have you tried to stop the NBFC service and restart it?

**Comment by oldbk** [comment]
yes, after restart NBFC service it pretty work. But this strange service "stagnation" after sleep, for what it can depend, approximately?

**Comment by hirschmann** [comment]
When NBFC can't access the EC, it just stops the service. I guess that's what you describe as stagnation.
Please give the latest beta a try. It should handle standby and hibernate much better.

**Comment by oldbk** [comment]
Greatful  thx you man. It`s seems stable than previous version ;)
