### ISSUE TITLE
nbfc service won't start

### ISSUE THREAD

**Issue by jeroenVranckx** [hirschmann/nbfc#213]
Hello, 
I'm currently trying to fix my constantly on fan on my asus ux310UA. On my last laptop nbfc worked like a charm, so I thought to myself, never change a winning combination :)

when i try to chose a configuration and try to enable the service, he will immediatly disable it again
I checked windows logs and came up with the following logs contained below.

Have you seen this issue before and do you mybe have an idea how to fix this?
tnx in advance ;)
if you want extra logs or system info, i can provide you with these if you want

------------------------------------------------------------------------------------------------------------------
Faulting application name: NbfcService.exe, version: 1.2.8.0, time stamp: 0x5666a662
Faulting module name: KERNELBASE.dll, version: 10.0.15063.0, time stamp: 0x461a0ff5
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process ID: 0xb28
Faulting application start time: 0x01d2b46f16e38ab3
Faulting application path: C:\Program Files (x86)\NoteBook FanControl\NbfcService.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 11322b8c-233b-422f-879d-aa763049d285
Faulting package full name: 
Faulting package-relative application ID: 

-------------------------------------------------------------------------------------------------------------------
Application: NbfcService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.PlatformNotSupportedException
   at StagWare.Hardware.HardwareMonitor.InitializeCpuSensors()
   at StagWare.Hardware.HardwareMonitor.get_CpuTemperatures()
   at StagWare.Plugins.Generic.CpuTemperatureMonitor.GetTemperature()
   at StagWare.FanControl.FanControl.TimerCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
---------------------------------------------------------------------------------------------------------------

Failed to access CPU temperature sensors(s).
   at StagWare.Hardware.HardwareMonitor.InitializeCpuSensors()
   at StagWare.Hardware.HardwareMonitor.get_CpuTemperatures()
   at StagWare.Plugins.Generic.CpuTemperatureMonitor.GetTemperature()
   at StagWare.FanControl.FanControl.TimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by hirschmann** [comment]
You use a version which does not support your CPU.
It should work with NBFC 1.5.0: https://github.com/hirschmann/nbfc/releases/tag/1.5.0
If it doesn't, give the latest nightly build a try: https://ci.appveyor.com/project/hirschmann/nbfc/build/artifacts

**Comment by jeroenVranckx** [comment]
Worked like a charm! thank you very much!

**Comment by Erriez** [comment]
Works perfect for me as well. Thanks!

**Comment by WildBiker1952** [comment]
Hello Stefan,
Please advise. NBFC was working perfectly. On Acer Aspire 7741. Using the 7741G profile. I installed a HP Ink tank printer & it's associated programs. after that NBFC wouldn't open. I uninstalled all of the HP software. Cleared cache & temps. Restarted & NBFC still not working. I uninstalled & reinstalled NBFC. It will not work now. Profile editor works fine & saves ok. Any help gratefully appreciated. Thank you.
