### ISSUE TITLE
Config editor empty

### ISSUE THREAD

**Issue by Somethingweirdhere** [hirschmann/nbfc#478]
I have tried to use the program on an Acer 593G, but the config window was empty. I tried reinstalling it but it didnt help. What might be wrong?

![image](https://user-images.githubusercontent.com/36226087/39664931-e8bdfc8c-508b-11e8-856c-57bf4b6ca36a.png)

**Comment by hirschmann** [comment]
You could try to stop the NBFC service, delete the service settings, and then restart it.
If this doesn't solve your problem, please post the service logs here.

https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview

**Comment by Devildude4427** [comment]
I'm not the original poster here, but I'm having the same issue. As you can see from the service logs, I've tried this a few times now. Once a config is originally chosen, it will be appear to be fine for a second, then all fan information disappears. The config menu will then stay blank until the service settings is deleted, and I repair using the setup exe. 

Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
    1393 May 18 14:34  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1388 May 18 14:34  Information NoteBookFanContro...            0 Service started successfully.
    1380 May 18 14:29  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1375 May 18 14:28  Information NoteBookFanContro...            0 Service started successfully.
    1363 May 18 14:17  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1358 May 18 14:16  Information NoteBookFanContro...            0 Service started successfully.
    1351 May 18 14:16  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1346 May 18 14:15  Information NoteBookFanContro...            0 Service started successfully.
    1335 May 18 14:02  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1330 May 18 14:01  Information NoteBookFanContro...            0 Service started successfully.
    1319 May 18 13:58  Information NoteBookFanContro...            0 Service started successfully.
    1317 May 18 13:58  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1295 May 18 13:54  Error       NoteBookFanContro...            0 Failed to access CPU temperature sensors(s)....
    1289 May 18 13:50  Information NoteBookFanContro...            0 Service started successfully.

**Comment by Devildude4427** [comment]
Not the original poster, but I'm having the same issue. After selecting a config file that I think should work (previous model of Acer laptop), it appears to all be fine for a moment, but then all information below "temperature" disappears, and the config selection menu is blank. The only way to fix it is by deleting the service settings and then running the repair on the install exe tool. This is the error I get: Failed to access CPU temperature sensors(s).
                                   rvice
                                                                        at StagWare.Hardware.HardwareMonitor.InitializeCpuSensors()
                                                                        at StagWare.Hardware.HardwareMonitor.get_CpuTemperatures()
                                                                        at StagWare.Plugins.Generic.CpuTemperatureMonitor.GetTemperature()
                                                                        at StagWare.FanControl.FanControl.TimerCallback(Object state)
                                                                        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                                                                        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                                                                        at System.Threading.TimerQueueTimer.CallCallback()
                                                                        at System.Threading.TimerQueueTimer.Fire()
                                                                        at System.Threading.TimerQueue.FireNextTimers()

I'm not sure if that's user error or not, as the settings seem to be the same between the config file that comes with the program and the laptop I'm using (Acer VN7-593G). So I doubt it is a user error issue, though of course that's not out of the question. Thanks for any help you can provide.
